### ISSUE TITLE
customize pictures

### ISSUE THREAD

**Issue by minhdoboi** [illim/freespectrogdx#13]
People are tired of these ugly pictures

**Comment by topcyprus** [comment]
already in progress

**Comment by illim** [comment]
The source image is here https://www.dropbox.com/s/ihf80xmrtbe12qe/images.tgz?dl=0
The atlas is generated with libgdx texturepacker.

I think the goal here is not to replace my pics but to distribute them separately so we don't have any licensing issue.

**Comment by topcyprus** [comment]
Cooler accepted usage of pictures and cards but we have to place link to spectromancer.com somewhere and text "game based on Spectromancer" or something like that

![clip2net_160630115751](https://cloud.githubusercontent.com/assets/4258642/16482774/11e8a9bc-3eba-11e6-9306-915d0ca1918c.png)
