### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by topcyprus** [illim/freespectrogdx#4]
Hey! Did you ever thought about multiplayer version of freespectrogdx? Can you contact me by email prospectro.net@gmail.com?

**Comment by illim** [comment]
a basic multiplayer has been added. Closing this one, for the bugs it will be new issues.

**Comment by topcyprus** [comment]
Great job! What about localization? Could you please help with adding multilingual card descriptions, we will translate into russian ourself.
